create table if not exists users
(
    id           bigint generated by default as identity
        primary key,
    created_at   timestamp(6) not null,
    deleted_at   timestamp(6),
    updated_at   timestamp(6),
    address      varchar(100) not null,
    email        varchar(50)  not null
        constraint uk6dotkott2kjsp8vw4d0m25fb7
            unique,
    username varchar(50) not null unique,
    full_name    varchar(100) not null,
    is_enabled   boolean default false,
    password     varchar(255),
    phone_number varchar(13)  not null,
    verification_code varchar not null,
    role         varchar(255)
        constraint users_role_check
            check ((role)::text = ANY ((ARRAY ['ADMIN'::character varying, 'USER'::character varying])::text[])),
    user_status  varchar(255) default 'INACTIVE'
        constraint users_user_status_check
            check ((user_status)::text = ANY
                   ((ARRAY ['ACTIVE'::character varying, 'BLOCKED'::character varying, 'INACTIVE'::character varying])::text[]))
);

create table if not exists publications
(
    id          bigint generated by default as identity
        primary key,
    created_at  timestamp(6) not null,
    deleted_at  timestamp(6),
    updated_at  timestamp(6),
    description varchar(100) not null,
    photo_name  varchar(255) not null,
    user_id     bigint
        constraint fk2utvp9h7ybh77dgki0cfw52c1
            references users
);

create table if not exists comments
(
    id             bigint generated by default as identity
        primary key,
    created_at     timestamp(6) not null,
    deleted_at     timestamp(6),
    updated_at     timestamp(6),
    comment        varchar(100) not null,
    publication_id bigint
        constraint fklpjwqhvr0p7e7x1u9efvaq6xe
            references publications,
    user_id        bigint
        constraint fk8omq0tc18jd43bu5tjh6jvraq
            references users
);

create table if not exists likes
(
    id             bigint generated by default as identity
        primary key,
    created_at     timestamp(6) not null,
    deleted_at     timestamp(6),
    updated_at     timestamp(6),
    publication_id bigint
        constraint fkpyogbn36rsoh4hp231acgeq1i
            references publications,
    user_id        bigint
        constraint fknvx9seeqqyy71bij291pwiwrg
            references users
);

create table if not exists subscriber_subscription
(
    id              bigint generated by default as identity
        primary key,
    created_at      timestamp(6) not null,
    deleted_at      timestamp(6),
    updated_at      timestamp(6),
    subscriber_id   bigint
        constraint fknwhd1w447pi1ywi2lqtnr9tac
            references users,
    subscription_id bigint
        constraint fkhb2kmaa5o93scfpe1dapoqfss
            references users
);

